-- MySQL Script generated by MySQL Workbench
-- 12/02/14 12:21:45
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema hipermedia
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `hipermedia` ;
USE `hipermedia` ;

-- -----------------------------------------------------
-- Table `hipermedia`.`actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`actor` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_actor_last_name` ON `hipermedia`.`actor` (`last_name` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`country`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`country` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`country` (
  `country_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `country` VARCHAR(50) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`country_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hipermedia`.`city`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`city` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`city` (
  `city_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `city` VARCHAR(50) NOT NULL,
  `country_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`city_id`),
  CONSTRAINT `fk_city_country`
    FOREIGN KEY (`country_id`)
    REFERENCES `hipermedia`.`country` (`country_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_country_id` ON `hipermedia`.`city` (`country_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`address`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`address` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`address` (
  `address_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `address` VARCHAR(50) NOT NULL,
  `address2` VARCHAR(50) NULL DEFAULT NULL,
  `district` VARCHAR(20) NOT NULL,
  `city_id` SMALLINT UNSIGNED NOT NULL,
  `postal_code` VARCHAR(10) NULL DEFAULT NULL,
  `phone` VARCHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`address_id`),
  CONSTRAINT `fk_address_city`
    FOREIGN KEY (`city_id`)
    REFERENCES `hipermedia`.`city` (`city_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_city_id` ON `hipermedia`.`address` (`city_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`category` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`category` (
  `category_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`category_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hipermedia`.`staff`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`staff` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`staff` (
  `staff_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `picture` BLOB NULL DEFAULT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `store_id` TINYINT UNSIGNED NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT TRUE,
  `username` VARCHAR(16) NOT NULL,
  `password` VARCHAR(40) BINARY NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`staff_id`),
  CONSTRAINT `fk_staff_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `hipermedia`.`store` (`store_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_staff_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `hipermedia`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_store_id` ON `hipermedia`.`staff` (`store_id` ASC);

CREATE INDEX `idx_fk_address_id` ON `hipermedia`.`staff` (`address_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`store` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`store` (
  `store_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `manager_staff_id` TINYINT UNSIGNED NOT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`store_id`),
  CONSTRAINT `fk_store_staff`
    FOREIGN KEY (`manager_staff_id`)
    REFERENCES `hipermedia`.`staff` (`staff_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_store_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `hipermedia`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX `idx_unique_manager` ON `hipermedia`.`store` (`manager_staff_id` ASC);

CREATE INDEX `idx_fk_address_id` ON `hipermedia`.`store` (`address_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`customer` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`customer` (
  `customer_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `store_id` TINYINT UNSIGNED NOT NULL,
  `first_name` VARCHAR(45) NOT NULL,
  `last_name` VARCHAR(45) NOT NULL,
  `email` VARCHAR(50) NULL DEFAULT NULL,
  `address_id` SMALLINT UNSIGNED NOT NULL,
  `active` TINYINT(1) NOT NULL DEFAULT TRUE,
  `create_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`customer_id`),
  CONSTRAINT `fk_customer_address`
    FOREIGN KEY (`address_id`)
    REFERENCES `hipermedia`.`address` (`address_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_customer_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `hipermedia`.`store` (`store_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COMMENT = 'Table storing all customers. Holds foreign keys to the addre' /* comment truncated */ /*s table and the store table where this customer is registered.

Basic information about the customer like first and last name are stored in the table itself. Same for the date the record was created and when the information was last updated.*/;

CREATE INDEX `idx_fk_store_id` ON `hipermedia`.`customer` (`store_id` ASC);

CREATE INDEX `idx_fk_address_id` ON `hipermedia`.`customer` (`address_id` ASC);

CREATE INDEX `idx_last_name` ON `hipermedia`.`customer` (`last_name` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`language`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`language` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`language` (
  `language_id` TINYINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` CHAR(20) NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`language_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `hipermedia`.`film`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`film` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`film` (
  `film_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  `release_year` YEAR NULL DEFAULT NULL,
  `language_id` TINYINT UNSIGNED NOT NULL,
  `original_language_id` TINYINT UNSIGNED NULL DEFAULT NULL,
  `rental_duration` TINYINT UNSIGNED NOT NULL DEFAULT 3,
  `rental_rate` DECIMAL(4,2) NOT NULL DEFAULT 4.99,
  `length` SMALLINT UNSIGNED NULL DEFAULT NULL,
  `replacement_cost` DECIMAL(5,2) NOT NULL DEFAULT 19.99,
  `rating` ENUM('G','PG','PG-13','R','NC-17') NULL DEFAULT 'G',
  `special_features` SET('Trailers','Commentaries','Deleted Scenes','Behind the Scenes') NULL DEFAULT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`),
  CONSTRAINT `fk_film_language`
    FOREIGN KEY (`language_id`)
    REFERENCES `hipermedia`.`language` (`language_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_language_original`
    FOREIGN KEY (`original_language_id`)
    REFERENCES `hipermedia`.`language` (`language_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_title` ON `hipermedia`.`film` (`title` ASC);

CREATE INDEX `idx_fk_language_id` ON `hipermedia`.`film` (`language_id` ASC);

CREATE INDEX `idx_fk_original_language_id` ON `hipermedia`.`film` (`original_language_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`film_actor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`film_actor` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`film_actor` (
  `actor_id` SMALLINT UNSIGNED NOT NULL,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`actor_id`, `film_id`),
  CONSTRAINT `fk_film_actor_actor`
    FOREIGN KEY (`actor_id`)
    REFERENCES `hipermedia`.`actor` (`actor_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_actor_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `hipermedia`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_film_id` ON `hipermedia`.`film_actor` (`film_id` ASC);

CREATE INDEX `fk_film_actor_actor_idx` ON `hipermedia`.`film_actor` (`actor_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`film_category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`film_category` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`film_category` (
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `category_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`film_id`, `category_id`),
  CONSTRAINT `fk_film_category_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `hipermedia`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_film_category_category`
    FOREIGN KEY (`category_id`)
    REFERENCES `hipermedia`.`category` (`category_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `fk_film_category_category_idx` ON `hipermedia`.`film_category` (`category_id` ASC);

CREATE INDEX `fk_film_category_film_idx` ON `hipermedia`.`film_category` (`film_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`film_text`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`film_text` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`film_text` (
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `title` VARCHAR(255) NOT NULL,
  `description` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`film_id`))
ENGINE = MyISAM;

CREATE FULLTEXT INDEX `idx_title_description` ON `hipermedia`.`film_text` (`title` ASC, `description` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`inventory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`inventory` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`inventory` (
  `inventory_id` MEDIUMINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `film_id` SMALLINT UNSIGNED NOT NULL,
  `store_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`inventory_id`),
  CONSTRAINT `fk_inventory_store`
    FOREIGN KEY (`store_id`)
    REFERENCES `hipermedia`.`store` (`store_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_inventory_film`
    FOREIGN KEY (`film_id`)
    REFERENCES `hipermedia`.`film` (`film_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_film_id` ON `hipermedia`.`inventory` (`film_id` ASC);

CREATE INDEX `idx_store_id_film_id` ON `hipermedia`.`inventory` (`store_id` ASC, `film_id` ASC);

CREATE INDEX `fk_inventory_store_idx` ON `hipermedia`.`inventory` (`store_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`rental`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`rental` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`rental` (
  `rental_id` INT NOT NULL AUTO_INCREMENT,
  `rental_date` DATETIME NOT NULL,
  `inventory_id` MEDIUMINT UNSIGNED NOT NULL,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `return_date` DATETIME NULL DEFAULT NULL,
  `staff_id` TINYINT UNSIGNED NOT NULL,
  `last_update` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`rental_id`),
  CONSTRAINT `fk_rental_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `hipermedia`.`staff` (`staff_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rental_inventory`
    FOREIGN KEY (`inventory_id`)
    REFERENCES `hipermedia`.`inventory` (`inventory_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_rental_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hipermedia`.`customer` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE UNIQUE INDEX ON `hipermedia`.`rental` (`rental_date` ASC, `inventory_id` ASC, `customer_id` ASC);

CREATE INDEX `idx_fk_inventory_id` ON `hipermedia`.`rental` (`inventory_id` ASC);

CREATE INDEX `idx_fk_customer_id` ON `hipermedia`.`rental` (`customer_id` ASC);

CREATE INDEX `idx_fk_staff_id` ON `hipermedia`.`rental` (`staff_id` ASC);


-- -----------------------------------------------------
-- Table `hipermedia`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `hipermedia`.`payment` ;

CREATE TABLE IF NOT EXISTS `hipermedia`.`payment` (
  `payment_id` SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
  `customer_id` SMALLINT UNSIGNED NOT NULL,
  `staff_id` TINYINT UNSIGNED NOT NULL,
  `rental_id` INT NULL DEFAULT NULL,
  `amount` DECIMAL(5,2) NOT NULL,
  `payment_date` DATETIME NOT NULL,
  `last_update` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`payment_id`),
  CONSTRAINT `fk_payment_rental`
    FOREIGN KEY (`rental_id`)
    REFERENCES `hipermedia`.`rental` (`rental_id`)
    ON DELETE SET NULL
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `hipermedia`.`customer` (`customer_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE,
  CONSTRAINT `fk_payment_staff`
    FOREIGN KEY (`staff_id`)
    REFERENCES `hipermedia`.`staff` (`staff_id`)
    ON DELETE RESTRICT
    ON UPDATE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;

CREATE INDEX `idx_fk_staff_id` ON `hipermedia`.`payment` (`staff_id` ASC);

CREATE INDEX `idx_fk_customer_id` ON `hipermedia`.`payment` (`customer_id` ASC);

CREATE INDEX `fk_payment_rental_idx` ON `hipermedia`.`payment` (`rental_id` ASC);


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
